import { describe, it, expect } from 'vitest'
import {
  CAPABILITY_CARD_CLOSING,
  CAPABILITY_CARD_MAX,
  CREATOR_STACK_GUARDRAIL,
  CREATOR_STACK_LIMITS,
  CREATOR_STACK_MD_INTRO,
  CREATOR_STACK_MD_TITLE,
  MIN_MATCH_SCORE,
  SEED_CREATOR_STACK,
  allCapabilities,
  emptyStack,
  findCapabilities,
  mergeSeed,
  normalizeStack,
  projectForPath,
  removeEntry,
  renderCapabilityCard,
  renderCreatorStackMarkdown,
  resolveDoc,
  seedEntries,
  slugId,
  upsertEntry
} from './creatorStack'
import { normPath } from './sessionLogic'
import { CREATOR_STACK_KINDS } from './types'
import type { CapabilityMatch, CreatorCapability, CreatorStack, CreatorStackEntry, Project } from './types'

const NOW = 1_700_000_000_000
const LATER = NOW + 60_000
const HOME = 'C:\\Users\\chris'

/** path.join stand-in for win32 (src/shared may not import node:path): backslashes,
 *  both separators accepted, `.` dropped, `..` resolved (the drive is kept). */
const winJoin = (...parts: string[]): string => {
  const segs: string[] = []
  for (const raw of parts.join('\\').split(/[\\/]+/)) {
    if (!raw || raw === '.') continue
    if (raw === '..') {
      if (segs.length > 1) segs.pop()
      continue
    }
    segs.push(raw)
  }
  return segs.join('\\')
}

const proj = (over: Partial<Project>): Project => ({
  id: 'x',
  name: 'X',
  path: 'C:\\Users\\chris\\proj',
  type: 'other',
  stack: '',
  status: 'active',
  favorite: false,
  notes: '',
  lastOpenedAt: null,
  createdAt: 0,
  updatedAt: 0,
  ...over
})

const cap = (over: Partial<CreatorCapability> & { id: string }): CreatorCapability => ({
  name: over.id,
  aliases: [],
  purpose: 'Does a thing.',
  entrypoints: [],
  docs: [],
  tags: [],
  ...over
})

const entry = (over: Partial<CreatorStackEntry> & { id: string }): CreatorStackEntry => ({
  name: over.id,
  aliases: [],
  path: `C:\\tools\\${over.id}`,
  kind: 'shared-tool',
  capabilities: [],
  docs: [],
  tags: [],
  exists: true,
  source: 'user',
  ...over
})

/** Every seed entry present on disk, no registered projects. */
const fullStack = (): CreatorStack =>
  mergeSeed(
    emptyStack(NOW),
    seedEntries(HOME, () => true, [], NOW, winJoin),
    NOW
  )

const byId = (stack: CreatorStack, id: string): CreatorStackEntry => {
  const e = stack.entries.find((x) => x.id === id)
  if (!e) throw new Error(`no entry ${id}`)
  return e
}

describe('SEED_CREATOR_STACK (verified-on-disk data — invariants only)', () => {
  it('has unique entry ids and unique capability ids', () => {
    const ids = SEED_CREATOR_STACK.map((s) => s.id)
    expect(new Set(ids).size).toBe(ids.length)
    const capIds = SEED_CREATOR_STACK.flatMap((s) => s.capabilities.map((c) => c.id))
    expect(new Set(capIds).size).toBe(capIds.length)
  })
  it('keeps every relPath relative to home with forward slashes and a valid kind', () => {
    for (const s of SEED_CREATOR_STACK) {
      expect(s.relPath).not.toMatch(/^[a-zA-Z]:|^[\\/]/)
      expect(s.relPath).not.toContain('\\')
      expect(CREATOR_STACK_KINDS).toContain(s.kind)
      expect(s.docs.length).toBeGreaterThan(0)
    }
  })
  it('carries the flagship trailer-kit capability under income-kit', () => {
    const kit = SEED_CREATOR_STACK.find((s) => s.id === 'income-kit')
    expect(kit?.capabilities.map((c) => c.id)).toContain('trailer-kit')
  })
})

describe('emptyStack', () => {
  it('is version 1 with no entries and the given timestamp', () => {
    expect(emptyStack(NOW)).toEqual({ version: 1, entries: [], updatedAt: NOW })
  })
})

describe('contract templates (literal spec text)', () => {
  it('pins the markdown title and intro, the card closing line and the three guardrail bullets', () => {
    expect(CREATOR_STACK_MD_TITLE).toBe(
      '# Creator Stack — shared tools & reusable projects (auto-generated by Builder Hub)'
    )
    expect(CREATOR_STACK_MD_INTRO).toBe(
      'Before building a new tool, look here. Each entry lists what it does, where it lives, and the docs to read FIRST.'
    )
    expect(CAPABILITY_CARD_CLOSING).toBe(
      'Use this tool rather than building a new one — adapt it per its README. Reference it freely; if you must change ITS source, say so explicitly first.'
    )
    expect(CREATOR_STACK_GUARDRAIL).toEqual([
      '- You may read and reference any of these freely (paths, docs, entrypoints) from any project.',
      '- Consume shared tools through their documented entrypoints instead of copying their implementation.',
      "- Before modifying another project's or tool's source, say so explicitly and prefer changes in the current project."
    ])
  })
})

describe('CREATOR_STACK_LIMITS', () => {
  it('is the single source for the card cap, the default match count and the score floor', () => {
    expect(CREATOR_STACK_LIMITS).toEqual({ cardChars: 900, matches: 3, minMatchScore: 4 })
    expect(CAPABILITY_CARD_MAX).toBe(CREATOR_STACK_LIMITS.cardChars)
    expect(MIN_MATCH_SCORE).toBe(CREATOR_STACK_LIMITS.minMatchScore)
  })
  it('findCapabilities defaults its limit to CREATOR_STACK_LIMITS.matches', () => {
    const stack = fullStack()
    const all = findCapabilities('trailer', stack, Infinity)
    expect(all.length).toBeGreaterThan(CREATOR_STACK_LIMITS.matches)
    expect(findCapabilities('trailer', stack)).toEqual(all.slice(0, CREATOR_STACK_LIMITS.matches))
  })
})

describe('normalizeStack', () => {
  it('returns an empty stack for anything that is not an object with an entries array', () => {
    for (const garbage of [null, undefined, 'x', 42, true, [], {}, { entries: 'nope' }, { entries: {} }]) {
      expect(normalizeStack(garbage, NOW)).toEqual(emptyStack(NOW))
    }
  })
  it('drops entries missing a string id/name/path or with an unknown kind', () => {
    const raw = {
      entries: [
        { id: 'ok', name: 'Ok', path: 'C:\\ok', kind: 'shared-tool' },
        { name: 'no id', path: 'C:\\x', kind: 'shared-tool' },
        { id: '', name: 'empty id', path: 'C:\\x', kind: 'shared-tool' },
        { id: 'no-name', path: 'C:\\x', kind: 'shared-tool' },
        { id: 'no-path', name: 'x', kind: 'shared-tool' },
        { id: 'bad-kind', name: 'x', path: 'C:\\x', kind: 'widget' },
        { id: 'no-kind', name: 'x', path: 'C:\\x' },
        'string',
        42,
        null,
        ['array']
      ]
    }
    const stack = normalizeStack(raw, NOW)
    expect(stack.entries.map((e) => e.id)).toEqual(['ok'])
  })
  it('fills defaults: aliases/docs/tags [], exists true, source user, capabilities []', () => {
    const stack = normalizeStack({ entries: [{ id: 'a', name: 'A', path: 'C:\\a', kind: 'playbook' }] }, NOW)
    expect(stack.entries[0]).toEqual({
      id: 'a',
      name: 'A',
      path: 'C:\\a',
      kind: 'playbook',
      aliases: [],
      docs: [],
      tags: [],
      capabilities: [],
      exists: true,
      source: 'user'
    })
    expect(stack.entries[0]).not.toHaveProperty('projectId')
    expect(stack.entries[0]).not.toHaveProperty('indexedAt')
    expect(stack.entries[0]).not.toHaveProperty('dependencies')
  })
  it('filters non-string / empty items out of the string arrays', () => {
    const stack = normalizeStack(
      {
        entries: [
          {
            id: 'a',
            name: 'A',
            path: 'C:\\a',
            kind: 'reference',
            aliases: ['ok', '', 3, null, '  ', 'fine'],
            docs: ['README.md', {}, ''],
            tags: 'not-an-array',
            dependencies: ['dep', 0]
          }
        ]
      },
      NOW
    )
    const e = stack.entries[0]
    expect(e.aliases).toEqual(['ok', 'fine'])
    expect(e.docs).toEqual(['README.md'])
    expect(e.tags).toEqual([])
    expect(e.dependencies).toEqual(['dep'])
  })
  it('validates capabilities the same way and de-duplicates their ids (first wins)', () => {
    const stack = normalizeStack(
      {
        entries: [
          {
            id: 'a',
            name: 'A',
            path: 'C:\\a',
            kind: 'shared-tool',
            capabilities: [
              { id: 'c1', name: 'C1', purpose: 'first', aliases: ['x'], worksFor: ['roblox', 'bogus', 7] },
              { id: 'c1', name: 'dupe', purpose: 'second' },
              { id: 'no-purpose', name: 'x' },
              { name: 'no-id', purpose: 'p' },
              { id: 'c2', name: 'C2', purpose: '', usageNotes: '', worksFor: 'nope', entrypoints: ['e', 1] },
              'garbage',
              null
            ]
          }
        ]
      },
      NOW
    )
    expect(stack.entries[0].capabilities).toEqual([
      {
        id: 'c1',
        name: 'C1',
        purpose: 'first',
        aliases: ['x'],
        entrypoints: [],
        docs: [],
        tags: [],
        worksFor: ['roblox']
      },
      { id: 'c2', name: 'C2', purpose: '', aliases: [], entrypoints: ['e'], docs: [], tags: [] }
    ])
    expect(stack.entries[0].capabilities[1]).not.toHaveProperty('usageNotes')
    expect(stack.entries[0].capabilities[1]).not.toHaveProperty('worksFor')
  })
  it('coerces exists/source/projectId/indexedAt to their valid shapes', () => {
    const stack = normalizeStack(
      {
        entries: [
          {
            id: 'a',
            name: 'A',
            path: 'C:\\a',
            kind: 'catalog',
            exists: 'yes',
            source: 'alien',
            projectId: ''
          },
          {
            id: 'b',
            name: 'B',
            path: 'C:\\b',
            kind: 'catalog',
            exists: false,
            source: 'discovered',
            projectId: 'p1',
            indexedAt: 5
          },
          { id: 'c', name: 'C', path: 'C:\\c', kind: 'catalog', source: 'seed', indexedAt: 'soon' }
        ]
      },
      NOW
    )
    const [a, b, c] = stack.entries
    expect(a.exists).toBe(true)
    expect(a.source).toBe('user')
    expect(a).not.toHaveProperty('projectId')
    expect(b.exists).toBe(false)
    expect(b.source).toBe('discovered')
    expect(b.projectId).toBe('p1')
    expect(b.indexedAt).toBe(5)
    expect(c.source).toBe('seed')
    expect(c).not.toHaveProperty('indexedAt')
  })
  it('keeps the first of duplicate entry ids', () => {
    const stack = normalizeStack(
      {
        entries: [
          { id: 'a', name: 'First', path: 'C:\\a', kind: 'profile' },
          { id: 'a', name: 'Second', path: 'C:\\a2', kind: 'profile' },
          { id: 'b', name: 'B', path: 'C:\\b', kind: 'profile' }
        ]
      },
      NOW
    )
    expect(stack.entries.map((e) => e.name)).toEqual(['First', 'B'])
  })
  it('forces version 1 and keeps a numeric updatedAt (else now)', () => {
    expect(normalizeStack({ version: 7, entries: [], updatedAt: 123 }, NOW)).toEqual({
      version: 1,
      entries: [],
      updatedAt: 123
    })
    expect(normalizeStack({ version: 'x', entries: [], updatedAt: 'yesterday' }, NOW).updatedAt).toBe(NOW)
    expect(normalizeStack({ entries: [], updatedAt: NaN }, NOW).updatedAt).toBe(NOW)
  })
  it('round-trips a seeded stack through JSON unchanged', () => {
    const stack = fullStack()
    expect(normalizeStack(JSON.parse(JSON.stringify(stack)), LATER)).toEqual(stack)
  })
})

describe('projectForPath', () => {
  const home = proj({ id: 'home', name: 'Home', path: 'C:\\Users\\chris' })
  const kit = proj({ id: 'kit', name: 'Income Kit', path: 'C:\\Users\\chris\\income-kit' })
  const projects = [home, kit]

  it('picks the LONGEST matching prefix, not the first registered', () => {
    expect(projectForPath('C:\\Users\\chris\\income-kit\\trailer-factory', projects)?.id).toBe('kit')
    expect(projectForPath('C:\\Users\\chris\\income-kit\\trailer-factory', [kit, home])?.id).toBe('kit')
    expect(projectForPath('C:\\Users\\chris\\TOOL-STACK.md', projects)?.id).toBe('home')
  })
  it('is case-insensitive and accepts forward slashes and trailing separators', () => {
    expect(projectForPath('c:/users/CHRIS/income-kit/', projects)?.id).toBe('kit')
    expect(
      projectForPath('C:\\USERS\\chris\\income-kit\\', [
        proj({ id: 'k', path: 'c:/users/chris/income-kit/' })
      ])?.id
    ).toBe('k')
  })
  it('counts an equal path as inside the project', () => {
    expect(projectForPath('C:\\Users\\chris\\income-kit', projects)?.id).toBe('kit')
  })
  it('does not match a sibling that merely shares a string prefix', () => {
    expect(projectForPath('C:\\Users\\chris\\income-kit-old\\x', [kit])).toBeUndefined()
    expect(projectForPath('C:\\Users\\christine\\x', [home])).toBeUndefined()
  })
  it('returns undefined for no projects, an unrelated drive, an empty path or garbage project paths', () => {
    expect(projectForPath('C:\\Users\\chris\\x', [])).toBeUndefined()
    expect(projectForPath('D:\\elsewhere', projects)).toBeUndefined()
    expect(projectForPath('', projects)).toBeUndefined()
    expect(projectForPath('C:\\Users\\chris\\x', [proj({ id: 'blank', path: '' })])).toBeUndefined()
    expect(projectForPath('C:\\x', [{ id: 'broken' } as unknown as Project])).toBeUndefined()
    expect(projectForPath('C:\\x', undefined as unknown as Project[])).toBeUndefined()
    expect(projectForPath('C:\\x', 'nope' as unknown as Project[])).toBeUndefined()
  })
  it('agrees with sessionLogic.normPath on which spellings are the same path', () => {
    const spellings = [
      'C:\\Users\\chris\\income-kit',
      'c:/users/CHRIS/income-kit/',
      'C:/Users\\chris/income-kit\\'
    ]
    for (const a of spellings) {
      for (const b of spellings) {
        expect(normPath(a)).toBe(normPath(b))
        expect(projectForPath(a, [proj({ id: 'k', path: b })])?.id).toBe('k')
      }
    }
    expect(normPath('C:\\Users\\chris\\income-kit-old')).not.toBe(normPath(spellings[0]))
    expect(
      projectForPath('C:\\Users\\chris\\income-kit-old', [proj({ id: 'k', path: spellings[0] })])
    ).toBeUndefined()
  })
  it('matches from a drive root or a UNC project path', () => {
    expect(projectForPath('C:\\Users\\x', [proj({ id: 'root', path: 'C:\\' })])?.id).toBe('root')
    expect(projectForPath('\\\\srv\\share\\p\\x', [proj({ id: 'unc', path: '//srv/share/p' })])?.id).toBe(
      'unc'
    )
  })
})

describe('seedEntries', () => {
  it('returns only the seeds whose resolved path exists, with backslash absolute paths', () => {
    const present = new Set([
      'C:\\Users\\chris\\income-kit',
      'C:\\Users\\chris\\.claude\\playbooks\\game-trailer-playbook.md'
    ])
    const seeded = seedEntries(HOME, (p) => present.has(p), [], NOW, winJoin)
    expect(seeded.map((e) => e.id)).toEqual(['income-kit', 'game-trailer-playbook'])
    expect(seeded[0].path).toBe('C:\\Users\\chris\\income-kit')
    expect(seeded[1].path).toBe('C:\\Users\\chris\\.claude\\playbooks\\game-trailer-playbook.md')
    for (const e of seeded) {
      expect(e.source).toBe('seed')
      expect(e.exists).toBe(true)
      expect(e.indexedAt).toBe(NOW)
    }
  })
  it('returns nothing when nothing is on disk and treats a throwing probe as missing', () => {
    expect(seedEntries(HOME, () => false, [], NOW, winJoin)).toEqual([])
    expect(
      seedEntries(
        HOME,
        () => {
          throw new Error('EACCES')
        },
        [],
        NOW,
        winJoin
      )
    ).toEqual([])
  })
  it('assigns projectId by longest prefix with two nested projects', () => {
    const home = proj({ id: 'home', path: 'C:\\Users\\chris' })
    const kit = proj({ id: 'kit', path: 'c:/users/chris/income-kit' })
    const seeded = seedEntries(HOME, () => true, [home, kit], NOW, winJoin)
    const ids = Object.fromEntries(seeded.map((e) => [e.id, e.projectId]))
    expect(ids['income-kit']).toBe('kit')
    expect(ids['game-trailer-playbook']).toBe('home')
    expect(ids['tool-stack']).toBe('home')
    expect(ids['everlight-trailer-reference']).toBe('home')
  })
  it('omits projectId entirely when no project contains the path', () => {
    const seeded = seedEntries(HOME, () => true, [proj({ id: 'far', path: 'D:\\other' })], NOW, winJoin)
    for (const e of seeded) expect(e).not.toHaveProperty('projectId')
  })
  it('copies capabilities and docs from the seed (no shared references)', () => {
    const seeded = seedEntries(HOME, () => true, [], NOW, winJoin)
    const kit = seeded.find((e) => e.id === 'income-kit')!
    const seedKit = SEED_CREATOR_STACK.find((s) => s.id === 'income-kit')!
    expect(kit.capabilities.map((c) => c.id)).toEqual(seedKit.capabilities.map((c) => c.id))
    expect(kit.docs).toEqual(seedKit.docs)
    expect(kit.tags).toEqual(seedKit.tags)
    kit.docs.push('MUTATED.md')
    kit.capabilities[0].aliases.push('mutated alias')
    kit.capabilities.pop()
    expect(seedKit.docs).not.toContain('MUTATED.md')
    expect(seedKit.capabilities[0].aliases).not.toContain('mutated alias')
    expect(seedKit.capabilities.length).toBe(5)
  })
  it('keeps usageNotes/worksFor only when the seed has them and always gives tags an array', () => {
    const seeded = seedEntries(HOME, () => true, [], NOW, winJoin)
    const trailer = allCapabilities({ version: 1, entries: seeded, updatedAt: NOW }).find(
      (x) => x.capability.id === 'trailer-kit'
    )!.capability
    expect(trailer.usageNotes).toMatch(/^Do NOT build a new trailer generator/)
    expect(trailer.worksFor).toEqual(['web-app', 'hytopia', 'roblox', 'unreal', 'mobile-app'])
    const catalog = allCapabilities({ version: 1, entries: seeded, updatedAt: NOW }).find(
      (x) => x.capability.id === 'tool-catalog'
    )!.capability
    expect(catalog).not.toHaveProperty('usageNotes')
    expect(catalog).not.toHaveProperty('worksFor')
    expect(catalog.tags).toEqual(['catalog'])
  })
})

describe('mergeSeed', () => {
  const seeded = (): CreatorStackEntry[] =>
    seedEntries(HOME, () => true, [proj({ id: 'inc', path: 'C:\\Users\\chris\\income-kit' })], LATER, winJoin)

  it('appends every seed the stack lacks, bumps updatedAt and returns a new object', () => {
    const before = emptyStack(NOW)
    const after = mergeSeed(before, seeded(), LATER)
    expect(after).not.toBe(before)
    expect(before.entries).toEqual([])
    expect(after.entries.map((e) => e.id)).toEqual(SEED_CREATOR_STACK.map((s) => s.id))
    expect(after.updatedAt).toBe(LATER)
    expect(after.version).toBe(1)
  })
  it('is idempotent on a second run apart from the timestamps', () => {
    const once = mergeSeed(emptyStack(NOW), seeded(), NOW)
    const twice = mergeSeed(once, seeded(), LATER)
    expect(twice.entries.length).toBe(once.entries.length)
    expect(twice.entries.map((e) => ({ ...e, indexedAt: 0 }))).toEqual(
      once.entries.map((e) => ({ ...e, indexedAt: 0 }))
    )
  })
  it('preserves user edits on a seed-sourced entry and refreshes only exists/projectId/indexedAt', () => {
    const edited = entry({
      id: 'income-kit',
      name: 'My renamed kit',
      aliases: ['my kit'],
      path: 'C:\\Users\\chris\\income-kit',
      capabilities: [cap({ id: 'only-one', usageNotes: 'my notes' })],
      docs: ['MY-NOTES.md'],
      tags: ['mine'],
      exists: false,
      projectId: 'stale',
      indexedAt: 1,
      source: 'seed'
    })
    const after = mergeSeed({ version: 1, entries: [edited], updatedAt: NOW }, seeded(), LATER)
    const kit = byId(after, 'income-kit')
    expect(kit.name).toBe('My renamed kit')
    expect(kit.aliases).toEqual(['my kit'])
    expect(kit.capabilities).toEqual([cap({ id: 'only-one', usageNotes: 'my notes' })])
    expect(kit.docs).toEqual(['MY-NOTES.md'])
    expect(kit.tags).toEqual(['mine'])
    expect(kit.path).toBe('C:\\Users\\chris\\income-kit')
    expect(kit.exists).toBe(true)
    expect(kit.projectId).toBe('inc')
    expect(kit.indexedAt).toBe(LATER)
    expect(after.entries.length).toBe(SEED_CREATOR_STACK.length)
  })
  it('adopts the seeded path when the stored path is marked missing', () => {
    const stale = entry({
      id: 'income-kit',
      path: 'C:\\old-place\\income-kit',
      exists: false,
      source: 'seed',
      aliases: ['kept alias']
    })
    const kit = byId(
      mergeSeed({ version: 1, entries: [stale], updatedAt: NOW }, seeded(), LATER),
      'income-kit'
    )
    expect(kit.path).toBe('C:\\Users\\chris\\income-kit')
    expect(kit.exists).toBe(true)
    expect(kit.projectId).toBe('inc')
    expect(kit.aliases).toEqual(['kept alias'])
  })
  it('keeps a stored path that differs but still exists (the user moved the tool)', () => {
    const moved = entry({
      id: 'income-kit',
      path: 'D:\\moved\\income-kit',
      exists: true,
      projectId: 'moved-proj',
      indexedAt: 1,
      source: 'seed'
    })
    const kit = byId(
      mergeSeed({ version: 1, entries: [moved], updatedAt: NOW }, seeded(), LATER),
      'income-kit'
    )
    expect(kit.path).toBe('D:\\moved\\income-kit')
    expect(kit.exists).toBe(true)
    expect(kit.projectId).toBe('moved-proj')
    expect(kit.indexedAt).toBe(LATER)
  })
  it('treats the same path spelled with other separators/case as the same path', () => {
    const spelled = entry({
      id: 'income-kit',
      path: 'c:/users/CHRIS/income-kit/',
      exists: false,
      source: 'seed'
    })
    const kit = byId(
      mergeSeed({ version: 1, entries: [spelled], updatedAt: NOW }, seeded(), LATER),
      'income-kit'
    )
    expect(kit.path).toBe('c:/users/CHRIS/income-kit/')
    expect(kit.exists).toBe(true)
    expect(kit.projectId).toBe('inc')
  })
  it('clears a stale projectId when the seed no longer resolves to a project', () => {
    const stored = entry({
      id: 'tool-stack',
      path: 'C:\\Users\\chris\\TOOL-STACK.md',
      projectId: 'gone',
      kind: 'catalog',
      source: 'seed'
    })
    const after = mergeSeed({ version: 1, entries: [stored], updatedAt: NOW }, seeded(), LATER)
    expect(byId(after, 'tool-stack')).not.toHaveProperty('projectId')
  })
  it('never touches user or discovered entries that share a seed id', () => {
    const user = entry({ id: 'income-kit', path: 'C:\\mine', exists: false, source: 'user', aliases: ['u'] })
    const disc = entry({
      id: 'tool-stack',
      path: 'C:\\found',
      exists: false,
      source: 'discovered',
      kind: 'catalog'
    })
    const after = mergeSeed({ version: 1, entries: [user, disc], updatedAt: NOW }, seeded(), LATER)
    expect(byId(after, 'income-kit')).toEqual(user)
    expect(byId(after, 'tool-stack')).toEqual(disc)
  })
  it('does not mutate the input stack or its entries', () => {
    const stored = entry({ id: 'income-kit', path: 'C:\\old', exists: false, source: 'seed' })
    const before: CreatorStack = { version: 1, entries: [stored], updatedAt: NOW }
    const snapshot = JSON.parse(JSON.stringify(before))
    mergeSeed(before, seeded(), LATER)
    expect(before).toEqual(snapshot)
  })
})

describe('upsertEntry / removeEntry', () => {
  const a = entry({ id: 'a' })
  const b = entry({ id: 'b' })
  const stack: CreatorStack = { version: 1, entries: [a, b], updatedAt: NOW }

  it('replaces an entry in place by id', () => {
    const a2 = entry({ id: 'a', name: 'A two' })
    const next = upsertEntry(stack, a2, LATER)
    expect(next.entries).toEqual([a2, b])
    expect(next.updatedAt).toBe(LATER)
    expect(stack.entries[0]).toBe(a)
  })
  it('appends an unknown id', () => {
    const c = entry({ id: 'c' })
    expect(upsertEntry(stack, c, LATER).entries.map((e) => e.id)).toEqual(['a', 'b', 'c'])
  })
  it('removes by id and bumps updatedAt', () => {
    const next = removeEntry(stack, 'a', LATER)
    expect(next.entries).toEqual([b])
    expect(next.updatedAt).toBe(LATER)
    expect(stack.entries.length).toBe(2)
  })
  it('returns the same stack when the id is unknown', () => {
    expect(removeEntry(stack, 'zzz', LATER)).toBe(stack)
  })
})

describe('findCapabilities', () => {
  const stack = fullStack()
  const top = (q: string, limit?: number): CapabilityMatch | undefined => findCapabilities(q, stack, limit)[0]

  it("'create a trailer using our trailer kit' → trailer-kit first, via the 'trailer kit' alias", () => {
    const matches = findCapabilities('create a trailer using our trailer kit', stack)
    expect(matches[0].capability?.id).toBe('trailer-kit')
    expect(matches[0].entry.id).toBe('income-kit')
    expect(matches[0].matched).toBe('trailer kit')
    expect(matches[1].capability?.id).toBe('trailer-method')
    expect(matches.length).toBeLessThanOrEqual(3)
  })
  it("'trailer' alone still matches trailer-kit, but scores lower than 'trailer kit'", () => {
    const bare = top('trailer')
    const phrase = top('trailer kit')
    expect(bare?.capability?.id).toBe('trailer-kit')
    expect(bare?.matched).toBe('trailer')
    expect(phrase?.capability?.id).toBe('trailer-kit')
    expect(phrase?.matched).toBe('trailer kit')
    expect(bare!.score).toBeLessThan(phrase!.score)
  })
  it("'video' alone → no matches (a lone tag hit never triggers a card)", () => {
    expect(findCapabilities('video', stack)).toEqual([])
    expect(findCapabilities('agents', stack)).toEqual([])
  })
  it("'which tools do i have' → tool-catalog", () => {
    expect(top('which tools do i have')?.capability?.id).toBe('tool-catalog')
  })
  it("'make a vertical tiktok video with the video factory' → video-factory first", () => {
    const matches = findCapabilities('make a vertical tiktok video with the video factory', stack)
    expect(matches[0].capability?.id).toBe('video-factory')
    expect(matches[0].matched).toBe('video factory')
  })
  it('lets tag hits ride along once an alias hit clears the bar, sorted by score then name', () => {
    const matches = findCapabilities('trailer', stack, 10)
    expect(matches[0].capability?.id).toBe('trailer-kit')
    expect(matches[0].score).toBeGreaterThanOrEqual(MIN_MATCH_SCORE)
    const rest = matches.slice(1)
    expect(rest.length).toBeGreaterThan(0)
    for (const m of rest) expect(m.score).toBeLessThan(matches[0].score)
    for (let i = 1; i < matches.length; i++) {
      const prev = matches[i - 1]
      const cur = matches[i]
      expect(prev.score).toBeGreaterThanOrEqual(cur.score)
      if (prev.score === cur.score) {
        const pn = (prev.capability?.name ?? prev.entry.name).toLowerCase()
        const cn = (cur.capability?.name ?? cur.entry.name).toLowerCase()
        expect(pn <= cn).toBe(true)
      }
    }
  })
  it('capability aliases beat entry aliases beat tags', () => {
    const s: CreatorStack = {
      version: 1,
      entries: [
        entry({ id: 'e1', aliases: ['zap'], tags: [] }),
        entry({ id: 'e2', capabilities: [cap({ id: 'c2', aliases: ['zap'] })] }),
        entry({ id: 'e3', tags: ['zap'] })
      ],
      updatedAt: NOW
    }
    const m = findCapabilities('please zap it', s, 10)
    expect(m.map((x) => x.capability?.id ?? x.entry.id)).toEqual(['c2', 'e1', 'e3'])
  })
  it('keeps the best score per entry+capability group and reports which phrase matched', () => {
    const s: CreatorStack = {
      version: 1,
      entries: [entry({ id: 'e', aliases: ['kit', 'the kit', 'the whole kit'], tags: ['kit'] })],
      updatedAt: NOW
    }
    const m = findCapabilities('use the whole kit', s)
    expect(m).toHaveLength(1)
    expect(m[0].matched).toBe('the whole kit')
    expect(m[0]).not.toHaveProperty('capability')
  })
  it('matches whole words only, case-insensitively, with flexible whitespace', () => {
    expect(top('TRAILER KIT')?.capability?.id).toBe('trailer-kit')
    expect(top('trailer   kit')?.capability?.id).toBe('trailer-kit')
    expect(findCapabilities('trailers', stack)).toEqual([])
    expect(findCapabilities('retrailer', stack)).toEqual([])
    expect(findCapabilities('trailer_kit', stack)).toEqual([])
    expect(top('the trailer-kit please')?.capability?.id).toBe('trailer-kit')
  })
  it('skips entries that are missing on disk', () => {
    const missing: CreatorStack = {
      version: 1,
      entries: stack.entries.map((e) => (e.id === 'income-kit' ? { ...e, exists: false } : e)),
      updatedAt: NOW
    }
    expect(findCapabilities('trailer kit', missing).some((m) => m.entry.id === 'income-kit')).toBe(false)
  })
  it('respects limit and returns nothing for empty/garbage queries or limits', () => {
    expect(findCapabilities('trailer', stack, 10).length).toBeGreaterThan(3)
    expect(findCapabilities('trailer', stack).length).toBeLessThanOrEqual(3)
    expect(findCapabilities('trailer', stack, 1)).toHaveLength(1)
    expect(findCapabilities('trailer', stack, 0)).toEqual([])
    expect(findCapabilities('trailer', stack, -2)).toEqual([])
    expect(findCapabilities('trailer', stack, NaN)).toEqual([])
    expect(findCapabilities('', stack)).toEqual([])
    expect(findCapabilities('   ', stack)).toEqual([])
    expect(findCapabilities(undefined as unknown as string, stack)).toEqual([])
    expect(findCapabilities('trailer', { version: 1, entries: [], updatedAt: NOW })).toEqual([])
    expect(findCapabilities('trailer', {} as CreatorStack)).toEqual([])
  })
  it('treats limit = Infinity as "no limit" (regression: it used to return nothing)', () => {
    const all = findCapabilities('trailer', stack, Infinity)
    expect(all.length).toBeGreaterThan(3)
    expect(all).toEqual(findCapabilities('trailer', stack, 1000))
    expect(findCapabilities('trailer', stack, -Infinity)).toEqual([])
  })
  it('keeps entry+capability groups apart even when ids contain spaces (regression: group key)', () => {
    const s: CreatorStack = {
      version: 1,
      entries: [
        entry({ id: 'a', capabilities: [cap({ id: 'b c', aliases: ['zap'] })] }),
        entry({ id: 'a b', capabilities: [cap({ id: 'c', aliases: ['zap zap'] })] })
      ],
      updatedAt: NOW
    }
    const m = findCapabilities('zap zap', s, 10)
    expect(m.map((x) => [x.entry.id, x.capability?.id, x.matched])).toEqual([
      ['a b', 'c', 'zap zap'],
      ['a', 'b c', 'zap']
    ])
  })
  it('uses Unicode-aware word boundaries (regression: "écafé" matched the alias "café")', () => {
    const s: CreatorStack = {
      version: 1,
      entries: [entry({ id: 'u', aliases: ['café', 'naïve tool'] })],
      updatedAt: NOW
    }
    expect(findCapabilities('écafé', s)).toEqual([])
    expect(findCapabilities('cafés', s)).toEqual([])
    expect(findCapabilities('the café please', s)[0]?.matched).toBe('café')
    expect(findCapabilities('THE CAFÉ', s)[0]?.matched).toBe('café')
    expect(findCapabilities('a naïve   tool', s)[0]?.matched).toBe('naïve tool')
  })
  it('never throws on aliases with regex metacharacters', () => {
    const s: CreatorStack = {
      version: 1,
      entries: [entry({ id: 'cpp', aliases: ['c++ (beta)', '[bracket] tool', 'a.b*c'], name: 'C++ (beta)' })],
      updatedAt: NOW
    }
    expect(findCapabilities('port it to c++ (beta) now', s)[0]?.entry.id).toBe('cpp')
    expect(findCapabilities('the [bracket] tool', s)[0]?.matched).toBe('[bracket] tool')
    expect(findCapabilities('aXbYc', s)).toEqual([])
  })
})

describe('slugId', () => {
  it('lowercases and collapses non-alphanumerics to single dashes', () => {
    expect(slugId('Trailer Factory (audio-first game trailers)')).toBe(
      'trailer-factory-audio-first-game-trailers'
    )
    expect(slugId('  Hello__World!!  ')).toBe('hello-world')
    expect(slugId('already-a-slug')).toBe('already-a-slug')
    expect(slugId('C:\\Users\\chris\\income-kit')).toBe('c-users-chris-income-kit')
  })
  it("falls back to 'entry' for empty or all-punctuation input", () => {
    expect(slugId('')).toBe('entry')
    expect(slugId('---')).toBe('entry')
    expect(slugId('!!! ???')).toBe('entry')
    expect(slugId(undefined as unknown as string)).toBe('entry')
  })
})

describe('resolveDoc', () => {
  const kit = entry({ id: 'income-kit', path: 'C:\\Users\\chris\\income-kit' })

  it("'.' (or blank) is the entry itself", () => {
    expect(resolveDoc(kit, '.', winJoin)).toBe('C:\\Users\\chris\\income-kit')
    expect(resolveDoc(kit, '', winJoin)).toBe('C:\\Users\\chris\\income-kit')
    expect(resolveDoc(kit, '  ', winJoin)).toBe('C:\\Users\\chris\\income-kit')
  })
  it('passes absolute paths through untouched', () => {
    expect(resolveDoc(kit, 'D:\\elsewhere\\doc.md', winJoin)).toBe('D:\\elsewhere\\doc.md')
    expect(resolveDoc(kit, 'c:/lower/drive.md', winJoin)).toBe('c:/lower/drive.md')
    expect(resolveDoc(kit, '/usr/share/doc.md', winJoin)).toBe('/usr/share/doc.md')
    expect(resolveDoc(kit, '\\\\server\\share\\doc.md', winJoin)).toBe('\\\\server\\share\\doc.md')
  })
  it('joins relative docs under the entry path (income-kit example)', () => {
    expect(resolveDoc(kit, 'trailer-factory/README.md', winJoin)).toBe(
      'C:\\Users\\chris\\income-kit\\trailer-factory\\README.md'
    )
    expect(resolveDoc(kit, 'trailer-factory\\PLAYBOOK.md', winJoin)).toBe(
      'C:\\Users\\chris\\income-kit\\trailer-factory\\PLAYBOOK.md'
    )
    expect(resolveDoc(kit, './video-factory//specs/', winJoin)).toBe(
      'C:\\Users\\chris\\income-kit\\video-factory\\specs'
    )
  })
  it('hands parent segments to joinPath (the Everlight reference docs)', () => {
    const ref = entry({ id: 'ref', path: 'C:\\Users\\chris\\Fable-5.1-one-shot\\tools' })
    expect(resolveDoc(ref, '../trailer/edit.json', winJoin)).toBe(
      'C:\\Users\\chris\\Fable-5.1-one-shot\\trailer\\edit.json'
    )
  })
  it('passes exactly the split segments to joinPath', () => {
    const calls: string[][] = []
    const spy = (...parts: string[]): string => {
      calls.push(parts)
      return parts.join('|')
    }
    resolveDoc(kit, 'a/b/c.md', spy)
    expect(calls).toEqual([['C:\\Users\\chris\\income-kit', 'a', 'b', 'c.md']])
  })
})

describe('renderCreatorStackMarkdown', () => {
  const md = renderCreatorStackMarkdown(fullStack(), '2026-09-16')

  it('opens with the title, the generated-on line and the intro', () => {
    expect(
      md.startsWith('# Creator Stack — shared tools & reusable projects (auto-generated by Builder Hub)\n')
    ).toBe(true)
    expect(md).toContain('Generated on 2026-09-16')
    expect(md).toContain(
      'Before building a new tool, look here. Each entry lists what it does, where it lives, and the docs to read FIRST.'
    )
  })
  it('renders every entry with kind, path, aliases and docs', () => {
    expect(md).toContain('## Income Kit\n- **Kind:** shared-tool\n- **Path:** `C:\\Users\\chris\\income-kit`')
    expect(md).toContain('- **Aliases:** income kit, side income kit, creator kit')
    expect(md).toContain(
      '- **Docs:** `C:\\Users\\chris\\income-kit\\START-HERE.md`, `C:\\Users\\chris\\income-kit\\CLAUDE.md`'
    )
    for (const s of SEED_CREATOR_STACK) expect(md).toContain(`## ${s.name}`)
    // '.' docs point at the entry itself
    expect(md).toContain(
      '## TOOL-STACK.md — master tool catalog\n- **Kind:** catalog\n- **Path:** `C:\\Users\\chris\\TOOL-STACK.md`'
    )
    expect(md).toContain('- **Docs:** `C:\\Users\\chris\\TOOL-STACK.md`')
  })
  it('renders each capability with purpose, read-first docs, entrypoints, notes, works-for and aliases', () => {
    expect(md).toContain('### Trailer Factory (audio-first game trailers) (`trailer-kit`)')
    expect(md).toContain('- **Purpose:** Create a 60–90 s cinematic game/product trailer')
    expect(md).toContain('- **Read first:** `C:\\Users\\chris\\income-kit\\trailer-factory\\README.md`')
    expect(md).toContain(
      '- **Entrypoints:** `C:\\Users\\chris\\income-kit\\trailer-factory\\tools\\build-trailer-audio.mjs`'
    )
    expect(md).toContain('- **Notes:** Do NOT build a new trailer generator.')
    expect(md).toContain('- **Works for:** web-app, hytopia, roblox, unreal, mobile-app')
    expect(md).toContain('- **Aliases:** trailer kit, trailer factory')
    // no entrypoints line for capabilities without any
    const marketing = md.slice(md.indexOf('### Roblox marketing engine'), md.indexOf('### Freelancing kit'))
    expect(marketing).not.toContain('**Entrypoints:**')
    expect(marketing).toContain('- **Works for:** roblox, hytopia')
  })
  it('flags entries missing on disk', () => {
    const s: CreatorStack = {
      version: 1,
      entries: [entry({ id: 'gone', name: 'Gone tool', path: 'C:\\gone', exists: false })],
      updatedAt: NOW
    }
    const out = renderCreatorStackMarkdown(s, 'today')
    expect(out).toContain('## Gone tool')
    expect(out).toContain('- **Missing on disk**')
    expect(md).not.toContain('- **Missing on disk**')
  })
  it('ends with the cross-project guardrail and its three bullets', () => {
    const tail = md.slice(md.indexOf('## Cross-project guardrail'))
    expect(CREATOR_STACK_GUARDRAIL).toHaveLength(3)
    for (const bullet of CREATOR_STACK_GUARDRAIL) expect(tail).toContain(bullet)
    expect(tail).toMatch(/read and reference any of these freely/)
    expect(tail).toMatch(/documented entrypoints instead of copying their implementation/)
    expect(tail).toMatch(/say so explicitly and prefer changes in the current project/)
    expect(md.endsWith('\n')).toBe(true)
  })
  it('renders an empty stack with the header, a placeholder and the guardrail', () => {
    const out = renderCreatorStackMarkdown(emptyStack(NOW), 'today')
    expect(out).toContain('# Creator Stack')
    expect(out).toContain('_No entries yet')
    expect(out).toContain('## Cross-project guardrail')
    expect(out).not.toContain('## undefined')
  })
  it('renders one full entry verbatim (golden: contract line order, extras after Missing on disk)', () => {
    const kit = entry({
      id: 'kit',
      name: 'Kit',
      kind: 'shared-tool',
      path: 'C:\\tools\\kit',
      aliases: ['the kit', 'kit'],
      docs: ['README.md', '/abs/doc.md'],
      projectId: 'p1',
      dependencies: ['ffmpeg'],
      tags: ['t1', 't2'],
      exists: false,
      capabilities: [
        cap({
          id: 'thing',
          name: 'Thing maker',
          aliases: ['thing maker'],
          purpose: 'Makes things.',
          entrypoints: ['bin/run.mjs', 'D:\\x\\y.cmd'],
          docs: ['docs/START.md'],
          usageNotes: 'Run it.',
          worksFor: ['web-app']
        })
      ]
    })
    const out = renderCreatorStackMarkdown({ version: 1, entries: [kit], updatedAt: NOW }, '2026-09-16')
    expect(out).toBe(
      [
        '# Creator Stack — shared tools & reusable projects (auto-generated by Builder Hub)',
        '',
        '_Generated on 2026-09-16. Do not edit by hand — Builder Hub regenerates this file from its Creator Stack registry._',
        '',
        'Before building a new tool, look here. Each entry lists what it does, where it lives, and the docs to read FIRST.',
        '',
        '## Kit',
        '- **Kind:** shared-tool',
        '- **Path:** `C:\\tools\\kit`',
        '- **Aliases:** the kit, kit',
        '- **Docs:** `C:\\tools\\kit\\README.md`, `/abs/doc.md`',
        '- **Missing on disk** — the path above was not found; fix or remove the entry in Builder Hub.',
        '- **Project:** p1',
        '- **Depends on:** ffmpeg',
        '- **Tags:** t1, t2',
        '',
        '### Thing maker (`thing`)',
        '- **Purpose:** Makes things.',
        '- **Read first:** `C:\\tools\\kit\\docs\\START.md`',
        '- **Entrypoints:** `C:\\tools\\kit\\bin\\run.mjs`; `D:\\x\\y.cmd`',
        '- **Notes:** Run it.',
        '- **Works for:** web-app',
        '- **Aliases:** thing maker',
        '',
        '## Cross-project guardrail',
        '- You may read and reference any of these freely (paths, docs, entrypoints) from any project.',
        '- Consume shared tools through their documented entrypoints instead of copying their implementation.',
        "- Before modifying another project's or tool's source, say so explicitly and prefer changes in the current project.",
        ''
      ].join('\n')
    )
  })
  it("falls back to the entry docs for a capability's Read first line and omits empty lines", () => {
    const e = entry({
      id: 'e',
      name: 'E',
      path: 'C:\\e',
      docs: ['GUIDE.md'],
      capabilities: [cap({ id: 'c', name: 'Cap', purpose: 'P.' })]
    })
    const out = renderCreatorStackMarkdown({ version: 1, entries: [e], updatedAt: NOW }, 'today')
    expect(out).toContain(
      '## E\n- **Kind:** shared-tool\n- **Path:** `C:\\e`\n- **Docs:** `C:\\e\\GUIDE.md`\n\n### Cap (`c`)\n- **Purpose:** P.\n- **Read first:** `C:\\e\\GUIDE.md`\n\n## Cross-project guardrail'
    )
    expect(out).not.toContain('**Aliases:**')
    expect(out).not.toContain('**Entrypoints:**')
    expect(out).not.toContain('**Notes:**')
    expect(out).not.toContain('**Works for:**')
    expect(out).not.toContain('**Tags:**')
    expect(out).not.toContain('**Project:**')
  })
})

describe('renderCapabilityCard', () => {
  const stack = fullStack()
  const trailerMatch = findCapabilities('trailer kit', stack)[0]
  const card = renderCapabilityCard(trailerMatch, winJoin)

  it('trailer-kit: names the tool, its path, the README to read first and the closing line, within 900 chars', () => {
    expect(
      card.startsWith(
        '[Builder Hub · Creator Stack] You already have an established tool for this: **Trailer Factory (audio-first game trailers)** — `C:\\Users\\chris\\income-kit`\n'
      )
    ).toBe(true)
    expect(card).toContain(
      'Read first (minimum needed): C:\\Users\\chris\\income-kit\\trailer-factory\\README.md'
    )
    expect(card).toContain('Purpose: Create a 60–90 s cinematic game/product trailer')
    expect(card).toContain(
      'Entrypoints: C:\\Users\\chris\\income-kit\\trailer-factory\\tools\\build-trailer-audio.mjs'
    )
    expect(card).toContain('Notes: Do NOT build a new trailer generator.')
    expect(card).toContain('Works for: web-app, hytopia, roblox, unreal, mobile-app')
    expect(card.endsWith('\n' + CAPABILITY_CARD_CLOSING)).toBe(true)
    expect(card.length).toBeLessThanOrEqual(900)
    expect(CAPABILITY_CARD_MAX).toBe(900)
  })
  it('renders a small capability verbatim (golden)', () => {
    const small = entry({
      id: 'kit',
      name: 'Kit',
      path: 'C:\\tools\\kit',
      docs: ['README.md'],
      capabilities: [
        cap({
          id: 'thing',
          name: 'Thing maker',
          aliases: ['thing maker'],
          purpose: 'Makes things.',
          entrypoints: ['bin/run.mjs'],
          docs: ['docs/START.md', '.'],
          usageNotes: 'Run it.',
          worksFor: ['web-app', 'roblox']
        })
      ]
    })
    const m = findCapabilities('use the thing maker', { version: 1, entries: [small], updatedAt: NOW })[0]
    expect(renderCapabilityCard(m, winJoin)).toBe(
      [
        '[Builder Hub · Creator Stack] You already have an established tool for this: **Thing maker** — `C:\\tools\\kit`',
        'Purpose: Makes things.',
        'Read first (minimum needed): C:\\tools\\kit\\docs\\START.md; C:\\tools\\kit',
        'Entrypoints: C:\\tools\\kit\\bin\\run.mjs',
        'Notes: Run it.',
        'Works for: web-app, roblox',
        CAPABILITY_CARD_CLOSING
      ].join('\n')
    )
  })
  it('omits Entrypoints/Notes/Works-for when absent and falls back to the entry docs, then the entry path', () => {
    const e = entry({
      id: 'e',
      name: 'Entry',
      path: 'C:\\e',
      docs: ['README.md'],
      capabilities: [cap({ id: 'c', name: 'Cap' })]
    })
    const m: CapabilityMatch = { entry: e, capability: e.capabilities[0], matched: 'cap', score: 5 }
    const out = renderCapabilityCard(m, winJoin)
    expect(out).toBe(
      [
        '[Builder Hub · Creator Stack] You already have an established tool for this: **Cap** — `C:\\e`',
        'Purpose: Does a thing.',
        'Read first (minimum needed): C:\\e\\README.md',
        CAPABILITY_CARD_CLOSING
      ].join('\n')
    )
    const bare = entry({ id: 'bare', name: 'Bare', path: 'C:\\bare' })
    const out2 = renderCapabilityCard({ entry: bare, matched: 'bare', score: 4 }, winJoin)
    expect(out2).toBe(
      [
        '[Builder Hub · Creator Stack] You already have an established tool for this: **Bare** — `C:\\bare`',
        'Read first (minimum needed): C:\\bare',
        CAPABILITY_CARD_CLOSING
      ].join('\n')
    )
  })
  it('uses the entry name and entry docs for an entry-level match', () => {
    const m = findCapabilities('open the subagents repo', stack)[0]
    expect(m.entry.id).toBe('subagents-repo')
    expect(m).not.toHaveProperty('capability')
    const out = renderCapabilityCard(m, winJoin)
    expect(out).toContain('**Subagents repo (19-agent pack source)** — `C:\\Users\\chris\\subagents-repo`')
    expect(out).toContain('Read first (minimum needed): C:\\Users\\chris\\subagents-repo\\README.md')
    expect(out).not.toContain('Purpose:')
    expect(out).not.toContain('Entrypoints:')
  })
  it('truncates Notes first (with an ellipsis) and leaves the other lines intact', () => {
    const longNotes = Array.from({ length: 120 }, (_, i) => `note${i}`).join(' ')
    const e = entry({
      id: 'e',
      path: 'C:\\e',
      capabilities: [
        cap({
          id: 'c',
          purpose: 'Short purpose.',
          entrypoints: ['run.mjs'],
          docs: ['README.md'],
          usageNotes: longNotes
        })
      ]
    })
    const out = renderCapabilityCard(
      { entry: e, capability: e.capabilities[0], matched: 'c', score: 5 },
      winJoin
    )
    expect(out.length).toBeLessThanOrEqual(900)
    expect(out).toContain('Purpose: Short purpose.')
    expect(out).toContain('Entrypoints: C:\\e\\run.mjs')
    expect(out).toContain('Read first (minimum needed): C:\\e\\README.md')
    const notes = out.split('\n').find((l) => l.startsWith('Notes: '))!
    expect(notes.endsWith('…')).toBe(true)
    expect(notes.startsWith('Notes: note0 note1 note2')).toBe(true)
    expect(out.endsWith(CAPABILITY_CARD_CLOSING)).toBe(true)
  })
  it('stays within the cap when everything is oversized, keeping the header and the closing line', () => {
    const huge = 'x'.repeat(2000)
    const e = entry({
      id: 'e',
      name: 'Huge',
      path: 'C:\\huge',
      capabilities: [
        cap({
          id: 'c',
          name: 'Huge cap',
          purpose: huge,
          entrypoints: Array.from({ length: 30 }, (_, i) => `tools/entry-${i}.mjs`),
          docs: Array.from({ length: 12 }, (_, i) => `docs/${i}.md`),
          usageNotes: huge,
          worksFor: ['web-app']
        })
      ]
    })
    const out = renderCapabilityCard(
      { entry: e, capability: e.capabilities[0], matched: 'c', score: 5 },
      winJoin
    )
    expect(out.length).toBeLessThanOrEqual(900)
    expect(
      out.startsWith(
        '[Builder Hub · Creator Stack] You already have an established tool for this: **Huge cap** — `C:\\huge`'
      )
    ).toBe(true)
    expect(out).toContain('Read first (minimum needed): C:\\huge\\docs\\0.md')
    expect(out.endsWith(CAPABILITY_CARD_CLOSING)).toBe(true)
  })
  it('does not throw on a capability that skipped normalizeStack (hook reply path)', () => {
    const e = entry({ id: 'g', name: 'G', path: 'C:\\g', docs: ['README.md'] })
    const garbage = {
      id: 'c',
      name: 'Cap',
      purpose: 7,
      docs: 'nope',
      worksFor: null
    } as unknown as CreatorCapability
    const out = renderCapabilityCard({ entry: e, capability: garbage, matched: 'cap', score: 5 }, winJoin)
    expect(out).toBe(
      [
        '[Builder Hub · Creator Stack] You already have an established tool for this: **Cap** — `C:\\g`',
        'Read first (minimum needed): C:\\g\\README.md',
        CAPABILITY_CARD_CLOSING
      ].join('\n')
    )
  })
  it('never exceeds the cap for any seeded capability', () => {
    for (const { entry: e, capability } of allCapabilities(stack)) {
      const out = renderCapabilityCard({ entry: e, capability, matched: capability.name, score: 5 }, winJoin)
      expect(out.length).toBeLessThanOrEqual(CAPABILITY_CARD_MAX)
      expect(out).toContain(e.path)
      expect(out.endsWith(CAPABILITY_CARD_CLOSING)).toBe(true)
    }
  })
})

describe('allCapabilities', () => {
  it('flattens every (entry, capability) pair in order', () => {
    const stack = fullStack()
    const pairs = allCapabilities(stack)
    const expected = SEED_CREATOR_STACK.flatMap((s) => s.capabilities.map((c) => [s.id, c.id]))
    expect(pairs.map((p) => [p.entry.id, p.capability.id])).toEqual(expected)
    expect(pairs.length).toBe(10)
  })
  it('is empty for an empty or malformed stack', () => {
    expect(allCapabilities(emptyStack(NOW))).toEqual([])
    expect(allCapabilities({} as CreatorStack)).toEqual([])
  })
})

describe('removed seed entries stay removed (integration review)', () => {
  it('removeEntry records a seed id and mergeSeed skips it; user entries are not recorded', () => {
    const seed = {
      id: 'income-kit',
      name: 'Income Kit',
      aliases: [],
      path: 'C:\\x',
      kind: 'shared-tool',
      capabilities: [],
      docs: [],
      exists: true,
      source: 'seed'
    } as CreatorStackEntry
    const user = { ...seed, id: 'mine', name: 'Mine', source: 'user' } as CreatorStackEntry
    let stack: CreatorStack = { version: 1, entries: [seed, user], updatedAt: 1 }
    stack = removeEntry(stack, 'income-kit', 2)
    expect(stack.removed).toEqual(['income-kit'])
    stack = removeEntry(stack, 'mine', 3)
    expect(stack.removed).toEqual(['income-kit'])
    const merged = mergeSeed(stack, [seed], 4)
    expect(merged.entries.find((e) => e.id === 'income-kit')).toBeUndefined()
    expect(merged.removed).toEqual(['income-kit'])
    // upsert (re-adding by hand) is still allowed
    expect(upsertEntry(merged, seed, 5).entries.some((e) => e.id === 'income-kit')).toBe(true)
    // normalizeStack round-trips the list and drops junk
    const round = normalizeStack({ version: 1, entries: [], removed: ['a', 'a', 3, ''], updatedAt: 1 }, 9)
    expect(round.removed).toEqual(['a'])
    expect(normalizeStack({ version: 1, entries: [], updatedAt: 1 }, 9).removed).toBeUndefined()
  })
})
