import { describe, it, expect } from 'vitest'
import {
  buildClaudeBuildPrompt,
  buildMvpPlanPrompt,
  defaultHandoffFilename,
  generateHandoff,
  slugifyForFilename
} from './handoff'
import type { HandoffInput, Project } from './types'

const proj = (over: Partial<Project>): Project => ({
  id: 'x',
  name: 'Squishy Smash',
  path: 'C:/Users/chris/Roblox-squishy',
  type: 'roblox',
  stack: 'Rojo · Luau · Meshy',
  status: 'active',
  favorite: false,
  notes: '',
  lastOpenedAt: null,
  createdAt: 0,
  updatedAt: 0,
  ...over
})

const input = (over: Partial<HandoffInput>): HandoffInput => ({
  taskTitle: 'Fix login flow',
  taskType: 'Bug fix',
  objective: 'Players cannot log in on mobile.',
  importantFiles: '',
  constraints: '',
  acceptanceCriteria: '',
  includeProjectContext: true,
  ...over
})

describe('slugifyForFilename', () => {
  it('lowercases and dashes non-alphanumerics', () =>
    expect(slugifyForFilename('Fix Login: Flow!!')).toBe('fix-login-flow'))
  it('falls back to untitled', () => expect(slugifyForFilename('***')).toBe('untitled'))
  it('caps length at 60', () => expect(slugifyForFilename('a'.repeat(80)).length).toBe(60))
})

describe('defaultHandoffFilename', () => {
  it('prefixes the date', () => {
    const d = new Date(2026, 6, 8) // July 8 2026, local
    expect(defaultHandoffFilename('Fix Login', d)).toBe('2026-07-08-fix-login.md')
  })
})

describe('generateHandoff', () => {
  it('includes title, task type, project block, and objective', () => {
    const md = generateHandoff(proj({ stage: 'building', url: 'https://roblox.com/games/1' }), input({}))
    expect(md).toContain('# Claude Code Handoff: Fix login flow')
    expect(md).toContain('**Task type:** Bug fix')
    expect(md).toContain('- Name: Squishy Smash')
    expect(md).toContain('- Type: Roblox (Rojo · Luau · Meshy)')
    expect(md).toContain('- Stage: Building')
    expect(md).toContain('- URL: https://roblox.com/games/1')
    expect(md).toContain('## Objective\nPlayers cannot log in on mobile.')
  })

  it('always includes the default constraints and appends extras', () => {
    const md = generateHandoff(proj({}), input({ constraints: 'No new deps\n  \nKeep Luau strict' }))
    expect(md).toContain('- Preserve existing architecture.')
    expect(md).toContain('- No new deps')
    expect(md).toContain('- Keep Luau strict')
  })

  it('renders files as bullets and acceptance criteria as checkboxes', () => {
    const md = generateHandoff(
      proj({}),
      input({ importantFiles: 'src/login.luau\nsrc/auth/', acceptanceCriteria: 'mobile login works' })
    )
    expect(md).toContain('- src/login.luau')
    expect(md).toContain('- [ ] mobile login works')
  })

  it('shows placeholders when lists are empty', () => {
    const md = generateHandoff(proj({}), input({}))
    expect(md).toContain('- (none specified)')
    expect(md).toContain('- [ ] (none specified)')
  })

  it('includes project context (brief, blockers, notes) when toggled on', () => {
    const p = proj({
      shortDescription: 'A smash game.',
      blockers: ['waiting on Meshy credits'],
      nextAction: 'ship v2',
      notes: 'promo videos in flight'
    })
    const md = generateHandoff(p, input({}))
    expect(md).toContain('## Project Context')
    expect(md).toContain('A smash game.')
    expect(md).toContain('- waiting on Meshy credits')
    expect(md).toContain('**Next action:** ship v2')
    expect(md).toContain('promo videos in flight')
  })

  it('omits project context when toggled off', () => {
    const p = proj({ shortDescription: 'A smash game.' })
    const md = generateHandoff(p, input({ includeProjectContext: false }))
    expect(md).not.toContain('## Project Context')
    expect(md).not.toContain('A smash game.')
  })

  it('never emits triple blank lines and ends with one newline', () => {
    const md = generateHandoff(proj({}), input({}))
    expect(md).not.toMatch(/\n{3,}/)
    expect(md.endsWith('\n')).toBe(true)
    expect(md.endsWith('\n\n')).toBe(false)
  })
})

describe('buildClaudeBuildPrompt', () => {
  it('renders the project brief', () => {
    const p = proj({
      shortDescription: 'A smash game.',
      problemSolved: 'Boredom.',
      stage: 'launch-prep'
    })
    const md = buildClaudeBuildPrompt(p, new Date(2026, 6, 8))
    expect(md).toContain('# Claude Code Build Prompt: Squishy Smash')
    expect(md).toContain('- **Stage:** Launch prep')
    expect(md).toContain('**Problem solved:** Boredom.')
    expect(md).toContain('Generated by Builder Hub')
  })
})

describe('buildMvpPlanPrompt', () => {
  it('splits the stack on · into bullets and falls back on next action', () => {
    const md = buildMvpPlanPrompt(proj({}), new Date(2026, 6, 8))
    expect(md).toContain('- Rojo\n- Luau\n- Meshy')
    expect(md).toContain('1. Define the next concrete action.')
  })

  it('uses shortDescription, then notes, then a placeholder', () => {
    expect(buildMvpPlanPrompt(proj({ shortDescription: 'Desc' }))).toContain('Desc')
    expect(buildMvpPlanPrompt(proj({ notes: 'note-body' }))).toContain('note-body')
    expect(buildMvpPlanPrompt(proj({}))).toContain('(no description yet)')
  })
})
